services:
  db:
    image: postgres:latest
    container_name: postgres_bachelor
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bachelor_dashboard
    ports:
      - '5432:5432' # Postgres port
    volumes:
      - postgres_data:/var/lib/postgresql/data

  blob:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    container_name: azurite_bachelor
    restart: unless-stopped
    ports:
      - '10000:10000' # Only need blob storage port
    command: azurite --blobHost 0.0.0.0 --blobPort 10000
    volumes:
      - azurite_data:/azurite-data

volumes:
  postgres_data:
  azurite_data:
