services:
  db:
    image: postgres:latest
    container_name: postgres_bachelor
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bachelor_dashboard
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  blob:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    container_name: azurite_bachelor
    restart: unless-stopped
    ports:
      - '10000:10000'
    command: azurite --blobHost 0.0.0.0 --blobPort 10000 --location /data
    volumes:
      - ./azurite:/data # Changed to use a local directory for better persistence
    
volumes:
  postgres_data: